packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  '@eslint/js': 9.39.1
  '@tailwindcss/postcss': 4.1.17
  "@tailwindcss/vite": 4.1.17
  '@tanstack/react-query': 5.90.7
  '@types/node': 24.10.0
  eslint: 9.39.1
  prettier: 3.6.2
  tailwindcss: 4.1.17
  typescript: 5.9.3
  vite: 7.2.2
  zod: 4.1.12

catalogs:
  react19:
    '@types/react': 19.1.12
    '@types/react-dom': 19.1.9
    react: 19.2.0
    react-dom: 19.2.0

linkWorkspacePackages: true

onlyBuiltDependencies:
  - esbuild

publicHoistPattern:
  - '@ianvs/prettier-plugin-sort-imports'
  - prettier-plugin-tailwindcss
